### ISSUE TITLE
Rework Framework class and optimize

### ISSUE THREAD

**Issue by Vortexdata** [Teamspeak-Query-Plugin-Framework/tsq-plugin-framework#56]
As of now, the framework class is bloated with variables, methods and generally is very cluttered, making it harder to maintain and develop.

**Comment by TAXSET** [comment]
New methods need to be implemented in order to get ticket #53 working properly.

**reload** _(used in framework command)_:
Should unload all plugins and restart the entire framework. Should not close connection to the server unless necessary.

**hibernate / sleep** _(used in reconnect strategies)_:
Should disconnect from the server and unload all plugins and prepare for wakeup event.

**wakeup** _(used in reconnect strategies)_:
Should re-establish connect to server and load all plugins.

**getStats** _(used in framework command)_:
Should return a FrameworkStat class which contains all information about the framework like hardware usage, ram size, system parameters, the current status of the framework (hibernating, waking up, running, crashed).

**Comment by TAXSET** [comment]
Also, ticket #58 requires a _getFramework()_ method, so keep this in mind.
